// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Game struct {
	Roomid int32
	Hei    sql.NullInt32
	Wid    sql.NullInt32
}

type Lobby struct {
	Userid sql.NullInt32
	Roomid sql.NullInt32
	ID     int32
}

type User struct {
	Userid int32
	Name   sql.NullString
}
